version: "3"
services:
  node:
    image: axieinfinity/ronin-mainnet:v2.1.0-74cc66b
    restart: always
    hostname: node
    container_name: node
    ports:
      - 127.0.0.1:8545:8545
      - 127.0.0.1:8546:8546
      - 30303:30303
      - 30303:30303/udp
    volumes:
      - ~/.skymavis/chaindata:/ronin
    environment:
      - PASSWORD=${PASSWORD}
      - PRIVATE_KEY=${VALIDATOR_PRIVATE_KEY}
      - BOOTNODES=${BOOTNODES}
      - NETWORK_ID=${NETWORK_ID}
      - ETHSTATS_ENDPOINT=${INSTANCE_NAME}:${CHAIN_STATS_WS_SECRET}@${CHAIN_STATS_WS_SERVER}:443
  bridge-db:
    image: postgres:13.1
    restart: always
    hostname: bridge-db
    container_name: bridge-db
    ports:
      - 127.0.0.1:54321:5432
    volumes:
      - ~/.skymavis/bridgedata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  bridge:
    image: axieinfinity/bridge:v0.2.0-1bef829
    restart: always
    hostname: bridge
    container_name: bridge
    depends_on:
      - node
      - bridge-db
    volumes:
      - ./config:/opt/config
    environment:
      - DEPLOYMENT=${DEPLOYMENT}
      - BRIDGE_DATABASE__URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@bridge-db:5432/${POSTGRES_DB}
      - BRIDGE_SECRET__PRIVATE_KEY=${VALIDATOR_PRIVATE_KEY}
      - BRIDGE_MAINCHAIN__ENDPOINT=${ETHEREUM_ENDPOINT}
      - BRIDGE_SIDECHAIN__ENDPOINT=http://node:8545
      - RUST_LOG=info
